type User {
	character: [Character] @relation
	email: String @unique
	role: String
}


type Character {
	user: String
	completed: Boolean!
	age: Number
	identity: String
	hair: String
	height: String
	sex: String
	skin: String
	weight: Number
	agility: Number
	brains: Number
	constitution: Number
	demeanor: Number
	acrobatics: Number
	larceny: Number
	ranged: Number
	stealth: Number
	medicine: Number
	perception: Number
	science: Number
	survival: Number
	athletics: Number
	build: Number
	drive: Number
	melee: Number
	leadership: Number
	perform: Number
	socialize: Number
	tame: Number
	luck: Number
	psyche: Number
	head: Number
	rightArm: Number
	leftArm: Number
	torso: Number
	leftLeg: Number
	rightLeg: Number
	abilities: [Ability]
	armor: [String]
	melee: [String]
	ranged: [String]
	ammo: [Ammo]
}

type Ability {
	name: String
	taken: Number
	options: String
}

type Ammo {
	name: String
	qty: Number
}