export default function(term) {
	const urlDictionary = {
		'Abilities': 'abilites',
		'Ability': 'abilities',
		'Absorption': 'combat/damage',
		'Acrobatics': 'skills/acrobatics',
		'Action': 'combat/actions',
		'Actions': 'combat/actions',
		'Active': 'combat/defense',
		'Agility': 'traits/agility',
		'Aim': 'maneuvers/aim',
		'Aiming': 'maneuvers/aim',
		'Ambidextrous': 'abilities/ambidextrous',
		'Asphyxiation': 'needs/asphyxiation',
		'Assassin': 'abilities/assassin',
		'Athletics': 'skills/athletics',
		'Attack': 'combat/attack',
		'Attacks': 'combat/attacks',
		'Bleeding': 'status/bleeding',
		'Blind': 'status/blind',
		'Blinded': 'status/blind',
		'Blinding': 'status/blind',
		'Block': 'skills/melee',
		'Botch': 'core/botch',
		'Botched': 'core/botch',
		'Botches': 'core/botch',
		'Botching': 'core/botch',
		'Brains': 'traits/brains',
		'Build': 'skills/build',
		'Burn': 'hazards/burn',
		'Burning': 'hazards/burning',
		'Called-Shot': 'maneuvers/calledshot',
		'Charge': 'abilities/charge',
		'Chase': 'combat/movement',
		'Combat': 'combat',
		'Communication': 'combat/communication',
		'Conceal': 'status/concealed',
		'Concealed': 'status/concealed',
		'Concealing': 'status/concealed',
		'Constitution': 'traits/constitution',
		'Cooperation': 'core/success',
		'Core': 'core',
		'Cover': 'status/cover',
		'Covered': 'status/cover',
		'Covering': 'status/cover',
		'Creation': 'creation',
		'Damaged': 'combat/damage',
		'Damage': 'combat/damage',
		'Deaf': 'status/deaf',
		'Deafened': 'status/deaf',
		'Defense': 'combat/defense',
		'Defenseless': 'status/defenseless',
		'Defenses': 'combat/defenses',
		'Deflection': 'properties/deflection',
		'Dehydration': 'needs/dehydration',
		'Demeanor': 'traits/demeanor',
		'Description': 'creation/description',
		'Dice': 'core/dice',
		'Difficulties': 'core/difficulty',
		'Difficulty': 'core/difficulty',
		'Disarm': 'maneuvers/disarm',
		'Disarmed': 'maneuvers/disarm',
		'Disarming': 'maneuvers/disarm',
		'Discipline': 'properties/discipline',
		'Disease': 'disease',
		'Diseases': 'disease',
		'Distract': 'maneuvers/distract',
		'Distracted': 'maneuvers/distract',
		'Distracting': 'maneuvers/distract',
		'Dodge': 'skills/acrobatics',
		'Drive': 'skills/drive',
		'Duck': 'maneuvers/duck',
		'Ducked': 'maneuvers/duck',
		'Ducking': 'maneuvers/duck',
		'Efficient Work': 'abilities/efficientwork',
		'Encourage': 'maneuvers/encourage',
		'Encouraged': 'maneuvers/encourage',
		'Encouraging': 'maneuvers/encourage',
		'Endurance': 'properties/endurance',
		'Evasion': 'properties/evasion',
		'Exhaustion': 'needs/exhaustion',
		'Experience': 'properties/experience',
		'Explode': 'core/explode',
		'Exploded': 'core/explode',
		'Explodes': 'core/explode',
		'Exploding': 'core/explode',
		'Explosion': 'core/explode',
		'Fail': 'core/fail',
		'Fails': 'core/fail',
		'Failed': 'core/fail',
		'Failing': 'core/fail',
		'Failure': 'core/fail',
		'Fall': 'hazards/falling',
		'Falling': 'hazards/falling',
		'Fast Draw': 'abilities/fastdraw',
		'Favorite Weapon': 'abilities/favoriteweapon',
		'Fire': 'combat/damage',
		'Firm Grip': 'abilities/firmgrip',
		'Fitness': 'properties/fitness',
		'Fleet Footed': 'abilities/fleetfooted',
		'Focus': 'abilities/focus',
		'Fortunate': 'abilities/fortunate',
		'Free Running': 'abilities/freerunning',
		'Friendly Fire': 'hazards/friendlyfire',
		'Grab': 'maneuvers/grapple',
		'Grabbed': 'status/grabbed',
		'Grabbing': 'maneuvers/grapple',
		'Grapple': 'maneuvers/grapple',
		'Grappling': 'maneuvers/grapple',
		'Hard Headed': 'abilities/hardheaded',
		'Harmless': 'status/harmless',
		'Hazard': 'hazards',
		'Hazards': 'hazards',
		'Health': 'properties/health',
		'Healthy': 'abilities/healthy',
		'Hidden': 'maneuvers/hide',
		'Hide': 'maneuvers/hide',
		'Hiding': 'maneuvers/hide',
		'Hostage': 'maneuvers/grapple',
		'Hyperimmunity': 'abilities/hyperimmunity',
		'Hypothermia': 'needs/hypothermia',
		'Immobilized': 'status/immobilized',
		'Intellect': 'properties/intellect',
		'Interrogate': 'maneuvers/interrogate',
		'Interrogated': 'maneuvers/interrogated',
		'Interrogating': 'maneuvers/interrogate',
		'Larceny': 'skills/larceny',
		'Leadership': 'skills/leadership',
		'Luck': 'properties/luck',
		'Maneuver': 'maneuvers',
		'Maneuvers': 'maneuvers',
		'Medicine': 'skills/medicine',
		'Melee': 'skills/melee',
		'Modifier': 'core/dice',
		'Modifiers': 'core/dice',
		'Movement': 'combat/movement',
		'Multilingual': 'abilities/multilingual',
		'Needs': 'needs',
		'Negotiate': 'maneuvers/negotiate',
		'Negotiated': 'maneuvers/negotiated',
		'Negotiating': 'maneuvers/negotiate',
		'Non-Lethal Force': 'maneuvers/nonlethalforce',
		'Off-Hand': 'status/offhand',
		'Pack Mentality': 'abilities/packmentality',
		'Pain Tolerance': 'abilities/paintolerance',
		'Pain': 'combat/pain',
		'Parry': 'abilities/parry',
		'Perception': 'skills/perception',
		'Perform': 'skills/perform',
		'Pin': 'status/pinned',
		'Pinned': 'status/pinned',
		'Pinning': 'status/pinned',
		'Practice': 'abilities/practice',
		'Projectile': 'skills/projectile',
		'Prone': 'status/prone',
		'Properties': 'properties',
		'Property': 'properties',
		'Protect': 'maneuvers/protect',
		'Protected': 'maneuvers/protect',
		'Protecting': 'maneuvers/protect',
		'Psyche': 'properties/psyche',
		'Push': 'maneuvers/push',
		'Pushed': 'maneuvers/push',
		'Pushing': 'maneuvers/push',
		'Radiation': 'hazards/radiation',
		'Range': 'status/range',
		'Recovery': 'combat/recovery',
		'Recover': 'combat/recovery',
		'Recruit': 'maneuvers/recruit',
		'Recruiting': 'maneuvers/recruit',
		'Reflexive': 'combat/defense',
		'Reload': 'maneuvers/reload',
		'Reloaded': 'maneuvers/reload',
		'Reloading': 'maneuvers/reload',
		'Restrain': 'status/restrained',
		'Restrained': 'status/restrained',
		'Restraining': 'status/restrained',
		'Result': 'core/dice',
		'Rote Action': 'core/success',
		'Rote Actions': 'core/success',
		'Round': 'combat/round',
		'Rounds': 'combat/round',
		'Science': 'skills/science',
		'Self Improvement': 'abilities/selfimprovement',
		'Shove': 'maneuvers/shove',
		'Shoved': 'maneuvers/shove',
		'Shoving': 'maneuvers/shove',
		'Sidestep': 'abilities/sidestep',
		'Situational Awareness': 'abilities/situationalawareness',
		'Skill': 'skills',
		'Skills': 'skills',
		'Sneak': 'maneuvers/sneak',
		'Sneaking': 'maneuvers/sneak',
		'Socialize': 'skills/socialize',
		'Specialize': 'abilities/specialize',
		'Speed': 'properties/speed',
		'Starvation': 'needs/starvation',
		'Status': 'status',
		'Statuses': 'status',
		'Stealth': 'skills/stealth',
		'Stun': 'status/stun',
		'Stunned': 'status/stun',
		'Stunning': 'status/stun',
		'Succeed': 'core/success',
		'Succeeds': 'core/success',
		'Succeeded': 'core/success',
		'Succeeding': 'core/success',
		'Success': 'core/success',
		'Successes': 'core/success',
		'Survival': 'skills/survival',
		'Tackle': 'maneuvers/tackle',
		'Tackled': 'maneuvers/tackle',
		'Tackling': 'maneuvers/tackle',
		'Tactical Reload': 'abilities/tacticalreload',
		'Tame': 'skills/tame',
		'Taunt': 'maneuvers/taunt',
		'Taunted': 'maneuvers/taunt',
		'Taunting': 'maneuvers/taunt',
		'Tenacity': 'abilities/tenacity',
		'Throw': 'maneuvers/throw',
		'Throwing': 'maneuvers/throw',
		'Thrown': 'maneuvers/throw',
		'Torture': 'maneuvers/torture',
		'Tortured': 'maneuvers/torture',
		'Torturing': 'maneuvers/torture',
		'Trait': 'traits',
		'Traits': 'traits',
		'Trauma': 'combat/trauma',
		'Trip': 'maneuvers/trip',
		'Tripped': 'maneuvers/trip',
		'Tripping': 'maneuvers/trip',
		'Unarmed': 'status/unarmed',
		'Unconscious': 'status/unconscious',
		'Unorthodox': 'abilities/unorthodox',
		'Unstable': 'status/unstable',
		'Vehicle Operation': 'abilities/vehicleoperation',
		'Visibility': 'status/visibility',
		'Weapon Training': 'abilities/weapontraining',
		'Wrestling': 'abilities/wrestling',
		'd6': 'core/dice',
		'Jump': 'skills/acrobatics',
		'Climb': 'skills/athletics',
		'Swim': 'skills/swim',
		'Customize': 'skills/build',
		'Repair': 'skills/repair',
		'Ram': 'skills/ram',
		'Stunt': 'skills/stunt',
		'Mechanical': 'skills/larceny',
		'Trick': 'skills/larceny',
		// 'Encourage': 'skills/leadership' NEED TO FIGURE OUT HOW TO DEAL WITH SKILLS AND MANEUVERS THAT OVERLAP
		'Intimidate': 'skills/leadership',
		'First-Aid': 'skills/medicine',
		'Surgery': 'skills/surgery',
		'Strike': 'skills/melee',
		'Search': 'skills/perception',
		'Intuition': 'skills/perception',
		// 'Distract': 'skills/perform' SAME PROBLEM AS WITH ENCOURAGE
		'Deceive': 'skills/perform',
		'Firearm': 'skills/projectile',
		'Traditional': 'skills/projectile',
		'Chemistry': 'skills/science',
		'Technology': 'skills/science',
		'Persuade': 'skills/socialize',
		'Therapy': 'skills/socialize',
		// 'Hide': 'skills/stealth', SAME PROBLEM
		// 'Sneak': 'skills/stealth SAME PROBLEM
		'Forage': 'skills/survival',
		'Foraging': 'skills/survival',
		'Command': 'skills/tame',
		'Train': 'skills/tame',
		'Size': 'properties/endurance'
	}
	if (urlDictionary.hasOwnProperty(term)) {
		return `/manual/${urlDictionary[term]}`
	} else {
		return null
	}
}