type Ability @embedded {
	i: String! @unique
	t: Int!
}

type Gear @embedded {
	i: String! @unique
	q: Int!
}

type Character {
	id: String! @unique
	Mu: String!
	Ms: String!
	Mc: Boolean!
	Mr: String!
	Ml: String!
	Mn: String
	Mm: String!
	Mx: Int!
	My: Int!
	Da: Int!
	Di: String!
	Dh: String!
	De: String!
	Ds: String!
	Sk: String!
	Dw: Int!
	Ta: Int!
	Tb: Int!
	Tc: Int!
	Td: Int!
	ac: Int!
	la: Int!
	ra: Int!
	st: Int!
	md: Int!
	pe: Int!
	sc: Int!
	su: Int!
	at: Int!
	bu: Int!
	dr: Int!
	me: Int!
	le: Int!
	pr: Int!
	so: Int!
	ta: Int!
	Pl: Int!
	Pp: Int!
	hD: Int!
	rA: Int!
	lA: Int!
	tO: Int!
	lL: Int!
	rL: Int!
	Ab: [Ability!]!
	Ga: [Gear!]!
	Gm: [Gear!]!
	Gr: [Gear!]!
	Go: [Gear!]!
	Ge: [Gear!]!
}