export default (c) => {
	return {
		user = c.user,
		completed = c.completed,
		age = c.description.age.value,
		identity = c.description.identity.value,
		hair = c.description.hair.value,
		height = c.description.height.value,
		sex = c.description.sex.value,
		skin = c.description.skin.value,
		weight = c.description.weight.value,
		agility = c.traits.agility.score,
		brains = c.traits.brains.score,
		constitution = c.traits.constitution.score,
		demeanor = c.traits.demeanor.score,
		acrobatics = c.skills.acrobatics.score,
		larceny = c.skills.larceny.score,
		ranged = c.skills.ranged.score,
		stealth = c.skills.stealth.score,
		medicine = c.skills.medicine.score,
		perception = c.skills.perception.score,
		science = c.skills.science.score,
		survival = c.skills.survival.score,
		athletics = c.skills.athletics.score,
		build = c.skills.build.score,
		drive = c.skills.drive.score,
		melee = c.skills.melee.score,
		leadership = c.skills.leadership.score,
		perform = c.skills.perform.score,
		socialize = c.skills.socialize.score,
		tame = c.skills.tame.score,
		luck = c.properties.luck.current,
		psyche = c.properties.psyche.current,
		head = c.health.head.current,
		rightArm = c.health.rightArm.current,
		leftArm = c.health.leftArm.current,
		torso = c.health.torso.current,
		leftLeg = c.health.leftLeg.current,
		rightLeg = c.health.rightLeg.current,
		abilities: [...c.abilities],
		armor: [...c.gear.armor],
		meleeWeapons: [...c.gear.meleeWeapons],
		rangedWeapons: [...c.gear.rangedWeapons],
		ammo: [...c.gear.ammo]
	}
}