type Character {
	i: String!
	u: String!
	s: String!
	c: Boolean!
	d: String!
	m: String!
	n: String
	p: String!
	x: Int!
	y: Int!
	Da: Int!
	Di: String!
	Dh: String!
	De: String!
	Ds: String!
	Sk: String!
	Dw: Int!
	A: Int!
	B: Int!
	C: Int!
	D: Int!
	acr: Int!
	lar: Int!
	ran: Int!
	ste: Int!
	med: Int!
	per: Int!
	sci: Int!
	sur: Int!
	ath: Int!
	bui: Int!
	dri: Int!
	mel: Int!
	lea: Int!
	prf: Int!
	soc: Int!
	tam: Int!
	L: Int!
	P: Int!
	hD: Int!
	rA: Int!
	lA: Int!
	tO: Int!
	lL: Int!
	rL: Int!
	# Ab: [Ability]
	# Gr: {
	# 	a: [Gear]
	# 	m: [Gear]
	# 	r: [Gear]
	# 	o: [Gear]
	# 	e: [Gear]
	# }
}

type Ability {
	i: String!
	q: Int!
	n: String
}

type Gear {
	i: String!
	q: Int!
	n: String
}

type Query {
	getCharacter(i: String): Character
}

mutation CreateCharacter {
	createCharacter(data: Value): Character
}