type Character {
	id: String!
	user: String!
	completed: Boolean!
	age: Int!
	identity: String!
	hair: String!
	height: String!
	sex: String!
	skin: String!
	weight: Int!
	agility: Int!
	brains: Int!
	constitution: Int!
	demeanor: Int!
	acrobatics: Int!
	larceny: Int!
	ranged: Int!
	stealth: Int!
	medicine: Int!
	perception: Int!
	science: Int!
	survival: Int!
	athletics: Int!
	build: Int!
	drive: Int!
	melee: Int!
	leadership: Int!
	perform: Int!
	socialize: Int!
	tame: Int!
	luck: Int!
}

type query {
	findCharacterById(id: String!): Character!
}

type mutation {
	createCharacter(character: Character!): Character!
}