import Gear from './Gear.js'

class Equipment extends Gear {
	constructor(name, description, sz) {
		super(name, description, sz)
	}
}

export const EquipmentList = [
	new Equipment(`Air Horn`,		   `Emits a loud shriek up to a 1 mile radius.`,	   1),
	new Equipment(`Balaclava`,		  `+1 Stealth. Mask. CR.`,							0),
	new Equipment(`Bandanna`,		   `+1 C vs airborne toxins. Can use as Bandage.`,	 0),
	new Equipment(`Baseball Cap`,	   `Reduce Visibility(Rain and Sun) penalty by 1.`,	0),
	new Equipment(`Bicycle`,			`Athletics 3#. Speed x3yds (x.7mph). 2h.`,		  8),
	new Equipment(`Binoculars`,		 `+3 Perception(See) at 50+yds.`,					1),
	new Equipment(`Bobby Pin`,		  `Allows Larceny(Disable) roll on key locks.`,	   0),
	new Equipment(`Bolt Cutters`,	   `C9# to cut metal (Handcuffs, Padlocks, etc).`,	 3),
	new Equipment(`Cage Trap`,		  `+3 Survival(Forage). Takes 1day.`,				 6),
	new Equipment(`Candle`,			 `1yd light radius for 6hrs.`,					   0),
	new Equipment(`Candy`,			  `Restores 1 Luck point. 1/day.`,					0),
	new Equipment(`Carabiner`,		  `+1 Athletics(Climb and Rappel). Holds 50Sz.`,	  0),
	new Equipment(`Compass`,			`+3 Survival(Navigate). Always points North.`,	  0),
	new Equipment(`Cowboy Hat`,		 `Reduce Visibility(Rain and Sun) penalty by 3.`,	0),
	new Equipment(`Chalk`,			  `Used to temporarily write on any surface.`,		0),
	new Equipment(`Chemical`,		   `Substances used for Science(Chemistry).`,		  1),
	new Equipment(`Choker Leash`,	   `+3 Tame. Grabbed. C +3 vs C to control.`,		  1),
	new Equipment(`Duct Tape`,		  `+1 Build/1yd or use 2yds as Handcuffs. 60yds.`,	1),
	new Equipment(`Dust Mask`,		  `+3 C vs airborne toxins. Mask.`,				   1),
	new Equipment(`Ear Plugs`,		  `No Deafness from noise. -3 Perception(Hear).`,	 9),
	new Equipment(`Egg Timer`,		  `Set up to 60mins. Loud ringing for 1min.`,		 1),
	new Equipment(`Fire-stick`,		 `+3 Survival(Camp). Magnesium rod and steel.`,	  0),
	new Equipment(`Fishing Pole`,	   `+1 Survival(Forage) at river, lake, or ocean.`,	2),
	new Equipment(`Flare Gun`,		  `Pistol. RNG:3. Ammo: 12g Flares or 1 use 12g.`,	1),
	new Equipment(`Flippers`,		   `+3 Athletics(Swim). -6 walking Speed.`,			2),
	new Equipment(`Food`,			   `Contains 1 Food to feed a person for a day.`,	  1),
	new Equipment(`Gas Mask`,		   `+6 C vs airborne toxins. Mask. -1 Perception.`,	1),
	new Equipment(`Glass Cutter`,	   `Cuts glass quietly.`,							  0),
	new Equipment(`Goggles`,			`+3 C to resist toxins in eyes.`,				   1),
	new Equipment(`Grappling Hook`,	 `+3 Athletics(Climb and Rappel). Holds 100Sz.`,	 2),
	new Equipment(`Gun Cleaning Kit`,   `Gun gets +1 RATK for 1day. Takes 1hr/gun.`,		1),
	new Equipment(`Hacksaw`,			`1DMG/rnd of sawing to almost any material.`,	   2),
	new Equipment(`Hammock`,			`Suspended sleeping device for 1 person.`,		  1),
	new Equipment(`Handcuffs`,		  `Grabbed. A15# to escape. Larceny(Disable) 12#.`,   1),
	new Equipment(`Leather Belt`,	   `1yd strap. Stops Limb Bleeding. Holds 50Sz.`,	  1),
	new Equipment(`Lifejacket`,		 `+6 Athletics(Swim). Prevents drowning.`,		   2),
	new Equipment(`Lighter`,			`Makes a small fire. 1yd radius light.`,			0),
	new Equipment(`Lockpicks`,		  `+3 Larceny(Disable) key locks. 6 picks.`,		  1),
	new Equipment(`Luxury Item`,		`Toilet paper, cigarette, etc. +1 Psyche 1/wk.`,	0),
	new Equipment(`Magnifying Glass`,   `+6 Perception(See) to inspect tiny details.`,	  1),
	new Equipment(`Makeup`,			 `+1 Socialize and Entertain for 6hrs. 30 uses.`,	0),
	new Equipment(`Marbles`,			`30/bag. 2sqyd area. A12# or fall Prone.`,		  1),
	new Equipment(`Marker`,			 `Used to permanently write on any surface.`,		0),
	new Equipment(`Matchbook`,		  `+1 Survival(Camp). 1yd light radius, 3rnds.`,	  0),
	new Equipment(`Measuring Cup`,	  `+3 Science(Chemistry). Marked glass cup.`,		 1),
	new Equipment(`Monocular`,		  `+1 Perception(See) at 25+yds.`,					1),
	new Equipment(`Multi-Tool`,		 `+1 Larceny(Disable), Build, Science(Tech).`,	   1),
	new Equipment(`Musical Instrument`, `+1 Entertain(Distract and Inspire).`,			  1),
	new Equipment(`Mylar Blanket`,	  `CR. 1yd x 2yd reflective foil sheet.`,			 0),
	new Equipment(`Notebook`,		   `100 pages of paper with a wire binding.`,		  1),
	new Equipment(`Padlock`,			`10HP. 6DR. Larceny(Disable) 9#.`,				  1),
	new Equipment(`Paracord`,		   `60yd coil. Holds 50Sz.`,						   1),
	new Equipment(`Part`,			   `Scrap used for Build and Science(Tech).`,		  1),
	new Equipment(`Pepper Spray`,	   `+1 Ranged(Gun). RNG:1. 3 Pain. 3 uses. Toxin.`,	0),
	new Equipment(`Pocket Mirror`,	  `Perception(See) 6# to see from behind Cover.`,	 0),
	new Equipment(`Poncho`,			 `CR. Waterproof.`,								  0),
	new Equipment(`Rat Trap`,		   `+1 Survival(Forage). Takes 1day.`,				 1),
	new Equipment(`Road Flare`,		 `3FDMG. 10yd light radius for 20mins.`,			 1),
	new Equipment(`Rollerblades`,	   `Athletics 6#. Speed x3. 1rnd equip. Fail:Prone.`,  2),
	new Equipment(`Rope`,			   `30yd nylon coil. Holds 100Sz.`,					2),
	new Equipment(`Running Shoes`,	  `+1 mile of Jogging distance.`,					 2),
	new Equipment(`Skateboard`,		 `Athletics 6#. Speed x3. Fail:Prone.`,			  3),
	new Equipment(`Sleeping Bag`,	   `Insulated bag for up to 2 people. CR +3hrs.`,	  3),
	new Equipment(`Snorkel`,			`Breathe while just beneath water's surface.`,	 1),
	new Equipment(`Spotting Scope`,	 `+6 Perception(See) at 100+yds.`,				   2),
	new Equipment(`Spray Paint`,		`RATK Called Shot:Head. Blind d6rnds. 10 uses.`,	1),
	new Equipment(`Sunglasses`,		 `No Visibility(Sun) penalty. +1 C vs light.`,	   0),
	new Equipment(`Swiss Army Knife`,   `+1 Build and Survival.`,						   1),
	new Equipment(`Tape Measure`,	   `+1 Build. 10yd long wind-up metal tape.`,		  2),
	new Equipment(`Tarp`,			   `3yd x 3yd plastic sheet. CR. Waterproof.`,		 1),
	new Equipment(`Tent`,			   `4 person. 5min setup/take-down. CR +3hrs.`,		6),
	new Equipment(`Thermal Underwear`,  `CR. Can use as 6 Bandages.`,					   1),
	new Equipment(`Tool Bag`,		   `+3 Build. Pliers, wrenches, level, etc.`,		  3),
	new Equipment(`Water Filter`,	   `Purifies 1 Water ration (.5gal) per minute.`,	  1),
	new Equipment(`Whetstone`,		  `Blade gets +1 DMG for 1day. Takes 1hr/blade.`,	 1),
	new Equipment(`Whistle`,			`+1 Tame(Train). Loud shriek 500yd radius.`,		0),
	new Equipment(`Wire Saw`,		   `1DMG/rnd of sawing to wood or bone.`,			  1),
	new Equipment(`Wristwatch`,		 `Tells time and +1 Survival(Navigate).`,			0),
	new Equipment(`Zip Tie`,			`Grabbed. C9# to escape. Use for +1 Build.`,		0)
]

// TODO: Check all item Notes.